import Head from 'next/head';
import Image from 'next/image';
import Header from '@/components/Header';
import Banner from '@/components/Banner';
import SmallCard from '@/components/SmallCard';
import MediumCard from '@/components/MediumCard';
import LargeCard from '@/components/LargeCard';
import Footer from '@/components/Footer';

export default function Home({ exploreData, cardsData }) {
	return (
		<div>
			<Head>
				<title>Airbnb</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Header />
			<Banner />
			<main className="max-w-7xl px-8 sm:px-16 mx-auto">
				<section className="pt-6">
					<h2 className="text-4xl font-semibold pb-5">Explore Nearby </h2>
					<div className="grid grid-cols sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4">
						{exploreData?.map((item) => {
							return <SmallCard key={item.img} {...item} />;
						})}
					</div>
				</section>
				<section>
					<h2 className="text-4xl font-semibold py-8">Live Anywhere</h2>
					<div className="flex gap-x-3 overflow-x-scroll !scrollbar-hide p-3 -ml-3">
						{cardsData.map((item) => {
							return <MediumCard key={item.img} {...item} />;
						})}
					</div>
				</section>
				<LargeCard
					img="https://links.papareact.com/4cj"
					title="The Greatest Outdoors"
					description="Wishlists curated by Airbnb"
					buttonText="Get Inspired"
				/>
			</main>
			<Footer />
		</div>
	);
}

export async function getStaticProps() {
	const res = await fetch('https://www.jsonkeeper.com/b/4G1G');
	const cardsData = await fetch('https://www.jsonkeeper.com/b/VHHT').then((res) => res.json());
	const data = await res.json();
	return {
		props: {
			exploreData: data,
			cardsData,
		},
	};
}
